version: '3'
services:
  postgres:
    image: postgres
    container_name: account_postgres
    restart: always
    ports:
      - "5442:5432"
    environment:
      POSTGRES_USER: account
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: account_db