spring:
  application:
    name: ms-account-service
  datasource:
    url: jdbc:postgresql://localhost:5442/account_db
    username: account
    password: 1234

  jpa:
    properties:
      hibernate:
        format_sql: true

    show-sql: true
    hibernate:

      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:db/change-master.yml


server:
  port: 8082


client:
  ms-auth-service:
    url: http://localhost:8081